"""Add opportunity resource timeline table

Revision ID: 160217620c86
Revises: 64b70a121ef6
Create Date: 2025-07-21 21:32:42.658925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '160217620c86'
down_revision: Union[str, Sequence[str], None] = '64b70a121ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_resource_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_line', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage_start_date', sa.DateTime(), nullable=False),
    sa.Column('stage_end_date', sa.DateTime(), nullable=False),
    sa.Column('duration_weeks', sa.Float(), nullable=False),
    sa.Column('fte_required', sa.Float(), nullable=False),
    sa.Column('total_effort_weeks', sa.Float(), nullable=False),
    sa.Column('opportunity_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tcv_millions', sa.Float(), nullable=True),
    sa.Column('decision_date', sa.DateTime(), nullable=False),
    sa.Column('calculated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.opportunity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_resource_timeline_category'), 'opportunity_resource_timeline', ['category'], unique=False)
    op.create_index(op.f('ix_opportunity_resource_timeline_opportunity_id'), 'opportunity_resource_timeline', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_resource_timeline_service_line'), 'opportunity_resource_timeline', ['service_line'], unique=False)
    op.create_index(op.f('ix_opportunity_resource_timeline_stage_end_date'), 'opportunity_resource_timeline', ['stage_end_date'], unique=False)
    op.create_index(op.f('ix_opportunity_resource_timeline_stage_name'), 'opportunity_resource_timeline', ['stage_name'], unique=False)
    op.create_index(op.f('ix_opportunity_resource_timeline_stage_start_date'), 'opportunity_resource_timeline', ['stage_start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_resource_timeline_stage_start_date'), table_name='opportunity_resource_timeline')
    op.drop_index(op.f('ix_opportunity_resource_timeline_stage_name'), table_name='opportunity_resource_timeline')
    op.drop_index(op.f('ix_opportunity_resource_timeline_stage_end_date'), table_name='opportunity_resource_timeline')
    op.drop_index(op.f('ix_opportunity_resource_timeline_service_line'), table_name='opportunity_resource_timeline')
    op.drop_index(op.f('ix_opportunity_resource_timeline_opportunity_id'), table_name='opportunity_resource_timeline')
    op.drop_index(op.f('ix_opportunity_resource_timeline_category'), table_name='opportunity_resource_timeline')
    op.drop_table('opportunity_resource_timeline')
    # ### end Alembic commands ###
