"""Initial migration - create all tables

Revision ID: 88586884907b
Revises: 
Create Date: 2025-07-21 13:03:57.418554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '88586884907b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity',
    sa.Column('opportunity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=False),
    sa.Column('assigned_resource', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_opportunity_id'), 'opportunity', ['opportunity_id'], unique=True)
    op.create_table('opportunitycategory',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_tcv', sa.Float(), nullable=False),
    sa.Column('max_tcv', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smeallocationrule',
    sa.Column('team_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_line', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('effort_per_million', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunitylineitem',
    sa.Column('opportunity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ces_revenue', sa.Float(), nullable=True),
    sa.Column('ins_revenue', sa.Float(), nullable=True),
    sa.Column('bps_revenue', sa.Float(), nullable=True),
    sa.Column('sec_revenue', sa.Float(), nullable=True),
    sa.Column('itoc_revenue', sa.Float(), nullable=True),
    sa.Column('mw_revenue', sa.Float(), nullable=True),
    sa.Column('tcv', sa.Float(), nullable=False),
    sa.Column('contract_length', sa.Float(), nullable=True),
    sa.Column('in_forecast', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.opportunity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stageeffortestimate',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_effort_weeks', sa.Float(), nullable=False),
    sa.Column('default_duration_weeks', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['opportunitycategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stageeffortestimate')
    op.drop_table('opportunitylineitem')
    op.drop_table('smeallocationrule')
    op.drop_table('opportunitycategory')
    op.drop_index(op.f('ix_opportunity_opportunity_id'), table_name='opportunity')
    op.drop_table('opportunity')
    # ### end Alembic commands ###
