"""Add ServiceLineOfferingThreshold table

Revision ID: 8dcdfabe29ff
Revises: c650e8bf8456
Create Date: 2025-07-25 10:57:39.620844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8dcdfabe29ff'
down_revision: Union[str, Sequence[str], None] = 'c650e8bf8456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicelineofferingthreshold',
    sa.Column('service_line', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_line_category_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('threshold_count', sa.Integer(), nullable=False),
    sa.Column('increment_multiplier', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_line_category_id'], ['servicelinecategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicelineofferingthreshold')
    # ### end Alembic commands ###
