"""Add user-managed fields to opportunity table

Revision ID: f87e3dc2e200
Revises: 160217620c86
Create Date: 2025-07-22 14:31:58.394043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f87e3dc2e200'
down_revision: Union[str, Sequence[str], None] = '160217620c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity', sa.Column('security_clearance', sa.String(), nullable=True))
    op.add_column('opportunity', sa.Column('custom_priority', sa.String(), nullable=True))
    op.add_column('opportunity', sa.Column('internal_stage_assessment', sa.String(), nullable=True))
    op.add_column('opportunity', sa.Column('custom_tracking_field_1', sa.String(), nullable=True))
    op.add_column('opportunity', sa.Column('custom_tracking_field_2', sa.String(), nullable=True))
    op.add_column('opportunity', sa.Column('custom_tracking_field_3', sa.String(), nullable=True))
    op.add_column('opportunity', sa.Column('internal_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity', 'internal_notes')
    op.drop_column('opportunity', 'custom_tracking_field_3')
    op.drop_column('opportunity', 'custom_tracking_field_2')
    op.drop_column('opportunity', 'custom_tracking_field_1')
    op.drop_column('opportunity', 'internal_stage_assessment')
    op.drop_column('opportunity', 'custom_priority')
    op.drop_column('opportunity', 'security_clearance')
    # ### end Alembic commands ###
