"""Add comprehensive opportunity and line item fields

Revision ID: faaa88ccf45c
Revises: 88586884907b
Create Date: 2025-07-21 18:27:37.943553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'faaa88ccf45c'
down_revision: Union[str, Sequence[str], None] = '88586884907b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quarterlyrevenue',
    sa.Column('opportunity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('q1_revenue', sa.Float(), nullable=True),
    sa.Column('q2_revenue', sa.Float(), nullable=True),
    sa.Column('q3_revenue', sa.Float(), nullable=True),
    sa.Column('q4_revenue', sa.Float(), nullable=True),
    sa.Column('fy_total', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.opportunity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('opportunity', sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('opportunity', sa.Column('sfdc_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('opportunity', sa.Column('opportunity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('opportunity', sa.Column('margin_percentage', sa.Float(), nullable=True))
    op.add_column('opportunity', sa.Column('first_year_revenue', sa.Float(), nullable=True))
    op.add_column('opportunity', sa.Column('second_year_revenue', sa.Float(), nullable=True))
    op.add_column('opportunity', sa.Column('revenue_beyond_year2', sa.Float(), nullable=True))
    op.add_column('opportunity', sa.Column('master_period', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('opportunity', sa.Column('lead_offering', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('opportunity', sa.Column('sales_org', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('opportunity', sa.Column('deal_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('opportunity', sa.Column('solution_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('opportunity', sa.Column('contract_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('opportunitylineitem', sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('opportunitylineitem', sa.Column('offering_margin', sa.Float(), nullable=True))
    op.add_column('opportunitylineitem', sa.Column('offering_margin_percentage', sa.Float(), nullable=True))
    op.add_column('opportunitylineitem', sa.Column('lead_offering_l2', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('opportunitylineitem', sa.Column('internal_service', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('opportunitylineitem', sa.Column('simplified_offering', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('opportunitylineitem', sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('opportunitylineitem', sa.Column('abr_revenue', sa.Float(), nullable=True))
    op.add_column('opportunitylineitem', sa.Column('iyr_revenue', sa.Float(), nullable=True))
    op.add_column('opportunitylineitem', sa.Column('iqr_revenue', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunitylineitem', 'iqr_revenue')
    op.drop_column('opportunitylineitem', 'iyr_revenue')
    op.drop_column('opportunitylineitem', 'abr_revenue')
    op.drop_column('opportunitylineitem', 'product_name')
    op.drop_column('opportunitylineitem', 'simplified_offering')
    op.drop_column('opportunitylineitem', 'internal_service')
    op.drop_column('opportunitylineitem', 'lead_offering_l2')
    op.drop_column('opportunitylineitem', 'offering_margin_percentage')
    op.drop_column('opportunitylineitem', 'offering_margin')
    op.drop_column('opportunitylineitem', 'account_name')
    op.drop_column('opportunity', 'contract_model')
    op.drop_column('opportunity', 'solution_type')
    op.drop_column('opportunity', 'deal_size')
    op.drop_column('opportunity', 'sales_org')
    op.drop_column('opportunity', 'lead_offering')
    op.drop_column('opportunity', 'master_period')
    op.drop_column('opportunity', 'revenue_beyond_year2')
    op.drop_column('opportunity', 'second_year_revenue')
    op.drop_column('opportunity', 'first_year_revenue')
    op.drop_column('opportunity', 'margin_percentage')
    op.drop_column('opportunity', 'opportunity_type')
    op.drop_column('opportunity', 'sfdc_url')
    op.drop_column('opportunity', 'account_name')
    op.drop_table('quarterlyrevenue')
    # ### end Alembic commands ###
